TrajectoryPlannerROS:

  holonomic_robot: false
  #mix_vel_x: -.1 #.4
  max_vel_x: .15
  #max_vel_theta: .5
  sim_time: 6.0
  controller_frequency: 9
  #path_distance_bias: 295
  #cost_scaling_factor: .5
  #vy_samples: 30
  #vth_samples: 30
  #min_in_place_vel_theta: 0.3
  #occdist_scale: 0.51 
