map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0

transform_tolerance: .2 #.3
cost_scaling_factor: 3.5  #3.5

inflation_radius: .76 #1.6
#footprint: [[-0.32, -0.320], [-0.322, 0.320], [0.322, 0.320], [0.322, -0.320]]
#footprint: [[-0.32, -0.0320], [-0.0322, 0.0320], [0.0322, 0.0320], [0.0322, -0.0320]]

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
